version: '3'

services:
  amkearame:
    build:
      context: .
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - TIMER=${TIMER}
    volumes:
      - ./telegram.session:/app/telegram.session
