version: '3'

services:
  get_session:
    build:
      context: .
    command: python get_session.py
    environment:
      - TELEGRAM_PROFILELESS_API_ID
      - TELEGRAM_PROFILELESS_API_HASH

  updater:
    build:
      context: .
    command: python updater.py
    environment:
      - TELEGRAM_PROFILELESS_API_ID
      - TELEGRAM_PROFILELESS_API_HASH
      - TELEGRAM_PROFILELESS_API_SESSION
      - TELEGRAM_PROFILELESS_PROVIDER
      - TELEGRAM_PROFILELESS_INTERVAL
    restart: unless-stopped
