version: '3'

services:
  amkearame:
    build:
      context: .
    environment:
      - AMKEARAME_API_ID=${API_ID}
      - AMKEARAME_API_HASH=${API_HASH}
      - AMKEARAME_DELAY=${TIMER}
    volumes:
      - ./telegram.session:/app/telegram.session
