version: '3'

services:
  amkearame:
    build:
      context: .
    environment:
      - AMKEARAME_API_ID=${AMKEARAME_API_ID}
      - AMKEARAME_API_HASH=${AMKEARAME_API_HASH}
      - AMKEARAME_DELAY=${AMKEARAME_DELAY}
    volumes:
      - ./telegram.session:/app/telegram.session
